datetime:
  extra:
    masks: dd/MM/yyyy


spring:
  application:
    name: veterinaria
  datasource:
    testWhileIdle: true
    test-on-borrow: true
    time-between-eviction-runs-millis: 18000
    init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
    validationQuery: SELECT 1
  data:
    rest:
      detection-strategy: annotated
      default-page-size:
      base-path: /api
