datetime:
  extra:
    masks: dd/MM/yyyy

spring:
  application:
    name: veterinaria
  profiles:
    active: production
  datasource:
    testWhileIdle: true
    test-on-borrow: true
    time-between-eviction-runs-millis: 18000
    init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
    validationQuery: SELECT 1
logging:
  config: classpath:logback-production.xml
  pattern:
    level: DEBUG
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg %n'
  
---
datetime:
  extra:
    masks: dd/MM/yyyy
    
gbfood:
  resources: 
    crawler: /tomcatfolder/app/gbfood/crawler/
    general: /tomcatfolder/app/
    lang: main.xml
    simy: simy.xml
logging:
  config: classpath:logback-production.xml
  pattern:
    level: DEBUG
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg %n'
spring:
  profiles: production
  datasource:
  # No olvidar poner jdbc:mysql://localhost:3306/vetetest?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true para que pille bien el UTF8 y reconecte bien
    jndi-name: java:comp/env/jdbc/veterinaria
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
    test-on-borrow: true
    time-between-eviction-runs-millis: 18000
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
    database-platform: org.hibernate.dialect.MySQLDialect

name: production

---
datetime:
  extra:
    masks: dd/MM/yyyy
    
gbfood:
  resources: 
    crawler: c:/opt/gf/
    general: c:/opt/gf/tmp/
    lang: main.xml
    simy: simy.xml
logging:
  config: classpath:logback-local.xml
spring:
  profiles: local
  jpa:
    properties:
      hibernate:
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/vetetest?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
    username: ilsaserver
    password: platano
    driverClassName: com.mysql.jdbc.Driver
    continueOnError: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 18000
    validationQuery: SELECT 1

name: local