package com.ikip.newsdetect.model;

public enum TypeEventEnum {
    SCRAP_FEED_START, SCRAP_FEED_END, SCRAP_FEED_FIRST_NEWS, SCRAP_FEED_LAST_LINK, FIND_ALERT_START, FIND_ALERT_END, FIND_LOCATION_START, FIND_LOCATION_END
}
